/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * CCNA Learning SaaS API foundation
 * OpenAPI spec version: 0.2.0
 */
import * as zod from 'zod';

/**
 * Returns only the authenticated user's attempts, newest first, using cursor-based pagination. Display details are opt-in and use the topic recorded at submission, even when the question moves or either record is disabled.
 * @summary List authenticated user's practice attempts
 */
export const getPracticeHistoryQueryLimitDefault = 20;
export const getPracticeHistoryQueryLimitMax = 100;

export const getPracticeHistoryQueryIncludeDetailsDefault = false;

export const GetPracticeHistoryQueryParams = zod.object({
  "limit": zod.number().int().min(1).max(getPracticeHistoryQueryLimitMax).default(getPracticeHistoryQueryLimitDefault),
  "cursor": zod.string().optional().describe('Opaque pagination cursor returned by a previous response.'),
  "includeDetails": zod.boolean().default(getPracticeHistoryQueryIncludeDetailsDefault).describe('Include nullable questionCode and topicName display fields. Omitted or false preserves the original response.')
})

export const GetPracticeHistoryResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().uuid(),
  "questionId": zod.string().uuid(),
  "topicId": zod.string().uuid(),
  "selectedOptionKey": zod.string(),
  "isCorrect": zod.boolean(),
  "submittedAt": zod.string().datetime({"offset":true}),
  "questionCode": zod.string().nullish().describe('Present only with includeDetails=true. Current question code; null if unavailable.'),
  "topicName": zod.string().nullish().describe('Present only with includeDetails=true. Current name of the topic recorded in the attempt, not the question\'s current topic; null if unavailable.')
})),
  "nextCursor": zod.string().nullable()
})
