/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * CCNA Learning SaaS API foundation
 * OpenAPI spec version: 0.2.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  GetPracticeHistoryParams,
  PracticeHistoryResponse
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetPracticeHistoryUrl = (params?: GetPracticeHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/practice/history?${stringifiedParams}` : `/api/practice/history`
}

/**
 * Returns only the authenticated user's attempts, newest first, using cursor-based pagination. Display details are opt-in and use the topic recorded at submission, even when the question moves or either record is disabled.
 * @summary List authenticated user's practice attempts
 */
export const getPracticeHistory = async (params?: GetPracticeHistoryParams, options?: Parameters<typeof customFetch>[1]): Promise<PracticeHistoryResponse> => {

  return customFetch<PracticeHistoryResponse>(getGetPracticeHistoryUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPracticeHistoryQueryKey = (params?: GetPracticeHistoryParams,) => {
    return [
    `/api/practice/history`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPracticeHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getPracticeHistory>>, TError = ErrorType<ErrorResponse>>(params?: GetPracticeHistoryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPracticeHistory>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPracticeHistoryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPracticeHistory>>> = ({ signal }) => getPracticeHistory(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPracticeHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPracticeHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getPracticeHistory>>>
export type GetPracticeHistoryQueryError = ErrorType<ErrorResponse>


/**
 * @summary List authenticated user's practice attempts
 */

export function useGetPracticeHistory<TData = Awaited<ReturnType<typeof getPracticeHistory>>, TError = ErrorType<ErrorResponse>>(
 params?: GetPracticeHistoryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPracticeHistory>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPracticeHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}
