/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * CCNA Learning SaaS API foundation
 * OpenAPI spec version: 0.2.0
 */
import * as zod from 'zod';

/**
 * Phase 5C.1 contract only; runtime implementation is scheduled for Phase 5C.2. Returns all-time historical attempt metrics and current available-catalog coverage for the authenticated internal user. Accepts no query parameters or request body; client-supplied userId is rejected. USER and ADMIN accounts receive only their own metrics. Does not include study time, streak days or average duration. See docs/api/learning-progress.md for cohort, rounding and topic-movement rules.
 * @summary Get the authenticated learner learning progress
 */
export const getLearningProgressResponseSummaryTotalAttemptsMin = 0;

export const getLearningProgressResponseSummaryCorrectAttemptsMin = 0;

export const getLearningProgressResponseSummaryOverallAccuracyMin = 0;
export const getLearningProgressResponseSummaryOverallAccuracyMax = 100;

export const getLearningProgressResponseSummaryUniqueQuestionsAttemptedMin = 0;

export const getLearningProgressResponseSummaryAvailableQuestionCountMin = 0;

export const getLearningProgressResponseSummaryCoveredQuestionCountMin = 0;

export const getLearningProgressResponseSummaryCoveragePercentMin = 0;
export const getLearningProgressResponseSummaryCoveragePercentMax = 100;

export const getLearningProgressResponseTopicsItemTopicNameMax = 180;

export const getLearningProgressResponseTopicsItemTotalAttemptsMin = 0;

export const getLearningProgressResponseTopicsItemCorrectAttemptsMin = 0;

export const getLearningProgressResponseTopicsItemAccuracyMin = 0;
export const getLearningProgressResponseTopicsItemAccuracyMax = 100;

export const getLearningProgressResponseTopicsItemUniqueQuestionsAttemptedMin = 0;

export const getLearningProgressResponseTopicsItemAvailableQuestionCountMin = 0;

export const getLearningProgressResponseTopicsItemCoveredQuestionCountMin = 0;

export const getLearningProgressResponseTopicsItemCoveragePercentMin = 0;
export const getLearningProgressResponseTopicsItemCoveragePercentMax = 100;



export const GetLearningProgressResponse = zod.object({
  "summary": zod.object({
  "totalAttempts": zod.number().int().min(getLearningProgressResponseSummaryTotalAttemptsMin).describe('All historical attempts belonging to the authenticated internal user, regardless of current question or topic status.'),
  "correctAttempts": zod.number().int().min(getLearningProgressResponseSummaryCorrectAttemptsMin).describe('Historical attempts whose stored is_correct value is true; never regraded from current answer options.'),
  "overallAccuracy": zod.number().min(getLearningProgressResponseSummaryOverallAccuracyMin).max(getLearningProgressResponseSummaryOverallAccuracyMax).describe('100 * correctAttempts / totalAttempts. This is attempt-weighted accuracy, not an average of topic percentages. Rounded to at most two decimal places; zero when the denominator is zero.'),
  "uniqueQuestionsAttempted": zod.number().int().min(getLearningProgressResponseSummaryUniqueQuestionsAttemptedMin).describe('Distinct question_id values across all historical attempts, including disabled or moved questions.'),
  "availableQuestionCount": zod.number().int().min(getLearningProgressResponseSummaryAvailableQuestionCountMin).describe('Current ACTIVE questions whose current topic is ACTIVE, including questions this user has never attempted.'),
  "coveredQuestionCount": zod.number().int().min(getLearningProgressResponseSummaryCoveredQuestionCountMin).describe('Distinct currently available questions for which this user has any historical attempt, regardless of its stored topic_id or correctness.'),
  "coveragePercent": zod.number().min(getLearningProgressResponseSummaryCoveragePercentMin).max(getLearningProgressResponseSummaryCoveragePercentMax).describe('100 * coveredQuestionCount / availableQuestionCount. Measures current catalog coverage, not mastery. Rounded to at most two decimal places; zero when the denominator is zero.')
}),
  "topics": zod.array(zod.object({
  "topicId": zod.string().uuid().describe('Existing topic ID. Matches stored attempt.topic_id for historical metrics and current question.topic_id for coverage.'),
  "topicName": zod.string().min(1).max(getLearningProgressResponseTopicsItemTopicNameMax).describe('Current topic name; historical names are not snapshotted.'),
  "status": zod.enum(['ACTIVE', 'DISABLED']).describe('Current topic status. A DISABLED topic is returned only when this user has historical attempts attributed to it.'),
  "displayOrder": zod.number().int().describe('Current catalog display order; topics are sorted by displayOrder, topicName, then topicId.'),
  "totalAttempts": zod.number().int().min(getLearningProgressResponseTopicsItemTotalAttemptsMin).describe('Historical attempts belonging to this user with stored topic_id equal to topicId.'),
  "correctAttempts": zod.number().int().min(getLearningProgressResponseTopicsItemCorrectAttemptsMin).describe('Those historical topic attempts with stored is_correct = true.'),
  "accuracy": zod.number().min(getLearningProgressResponseTopicsItemAccuracyMin).max(getLearningProgressResponseTopicsItemAccuracyMax).describe('100 * correctAttempts / totalAttempts for this historical topic cohort. Rounded to at most two decimal places; zero when the denominator is zero.'),
  "uniqueQuestionsAttempted": zod.number().int().min(getLearningProgressResponseTopicsItemUniqueQuestionsAttemptedMin).describe('Distinct question_id values in this user historical attempts attributed to this topic; includes disabled or subsequently moved questions.'),
  "availableQuestionCount": zod.number().int().min(getLearningProgressResponseTopicsItemAvailableQuestionCountMin).describe('Current ACTIVE questions assigned to this topic when the topic is ACTIVE; zero for a DISABLED topic.'),
  "coveredQuestionCount": zod.number().int().min(getLearningProgressResponseTopicsItemCoveredQuestionCountMin).describe('Distinct currently available questions in this topic with any historical attempt by this user, including attempts originally attributed to another topic.'),
  "coveragePercent": zod.number().min(getLearningProgressResponseTopicsItemCoveragePercentMin).max(getLearningProgressResponseTopicsItemCoveragePercentMax).describe('100 * coveredQuestionCount / availableQuestionCount for this current topic catalog. Rounded to at most two decimal places; zero when the denominator is zero.')
})).describe('All ACTIVE topics plus DISABLED topics with this user historical attempts, sorted by displayOrder, topicName, topicId. No unrelated disabled topics are exposed.')
})
