/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * CCNA Learning SaaS API foundation
 * OpenAPI spec version: 0.2.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  LearningProgressResponse
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetLearningProgressUrl = () => {




  return `/api/learning/progress`
}

/**
 * Phase 5C.1 contract only; runtime implementation is scheduled for Phase 5C.2. Returns all-time historical attempt metrics and current available-catalog coverage for the authenticated internal user. Accepts no query parameters or request body; client-supplied userId is rejected. USER and ADMIN accounts receive only their own metrics. Does not include study time, streak days or average duration. See docs/api/learning-progress.md for cohort, rounding and topic-movement rules.
 * @summary Get the authenticated learner learning progress
 */
export const getLearningProgress = async ( options?: Parameters<typeof customFetch>[1]): Promise<LearningProgressResponse> => {

  return customFetch<LearningProgressResponse>(getGetLearningProgressUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLearningProgressQueryKey = () => {
    return [
    `/api/learning/progress`
    ] as const;
    }


export const getGetLearningProgressQueryOptions = <TData = Awaited<ReturnType<typeof getLearningProgress>>, TError = ErrorType<ErrorResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLearningProgress>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLearningProgressQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLearningProgress>>> = ({ signal }) => getLearningProgress({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLearningProgress>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLearningProgressQueryResult = NonNullable<Awaited<ReturnType<typeof getLearningProgress>>>
export type GetLearningProgressQueryError = ErrorType<ErrorResponse>


/**
 * @summary Get the authenticated learner learning progress
 */

export function useGetLearningProgress<TData = Awaited<ReturnType<typeof getLearningProgress>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLearningProgress>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetLearningProgressQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}
