/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * CCNA Learning SaaS API foundation
 * OpenAPI spec version: 0.2.0
 */
export interface LearningProgressSummary {
  /**
     * All historical attempts belonging to the authenticated internal user, regardless of current question or topic status.
     * @minimum 0
     */
  totalAttempts: number;
  /**
     * Historical attempts whose stored is_correct value is true; never regraded from current answer options.
     * @minimum 0
     */
  correctAttempts: number;
  /**
     * 100 * correctAttempts / totalAttempts. This is attempt-weighted accuracy, not an average of topic percentages. Rounded to at most two decimal places; zero when the denominator is zero.
     * @minimum 0
     * @maximum 100
     */
  overallAccuracy: number;
  /**
     * Distinct question_id values across all historical attempts, including disabled or moved questions.
     * @minimum 0
     */
  uniqueQuestionsAttempted: number;
  /**
     * Current ACTIVE questions whose current topic is ACTIVE, including questions this user has never attempted.
     * @minimum 0
     */
  availableQuestionCount: number;
  /**
     * Distinct currently available questions for which this user has any historical attempt, regardless of its stored topic_id or correctness.
     * @minimum 0
     */
  coveredQuestionCount: number;
  /**
     * 100 * coveredQuestionCount / availableQuestionCount. Measures current catalog coverage, not mastery. Rounded to at most two decimal places; zero when the denominator is zero.
     * @minimum 0
     * @maximum 100
     */
  coveragePercent: number;
}

/**
 * Current topic status. A DISABLED topic is returned only when this user has historical attempts attributed to it.
 */
export type LearningTopicProgressStatus = typeof LearningTopicProgressStatus[keyof typeof LearningTopicProgressStatus];


export const LearningTopicProgressStatus = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
} as const;

export interface LearningTopicProgress {
  /** Existing topic ID. Matches stored attempt.topic_id for historical metrics and current question.topic_id for coverage. */
  topicId: string;
  /**
     * Current topic name; historical names are not snapshotted.
     * @minLength 1
     * @maxLength 180
     */
  topicName: string;
  /** Current topic status. A DISABLED topic is returned only when this user has historical attempts attributed to it. */
  status: LearningTopicProgressStatus;
  /** Current catalog display order; topics are sorted by displayOrder, topicName, then topicId. */
  displayOrder: number;
  /**
     * Historical attempts belonging to this user with stored topic_id equal to topicId.
     * @minimum 0
     */
  totalAttempts: number;
  /**
     * Those historical topic attempts with stored is_correct = true.
     * @minimum 0
     */
  correctAttempts: number;
  /**
     * 100 * correctAttempts / totalAttempts for this historical topic cohort. Rounded to at most two decimal places; zero when the denominator is zero.
     * @minimum 0
     * @maximum 100
     */
  accuracy: number;
  /**
     * Distinct question_id values in this user historical attempts attributed to this topic; includes disabled or subsequently moved questions.
     * @minimum 0
     */
  uniqueQuestionsAttempted: number;
  /**
     * Current ACTIVE questions assigned to this topic when the topic is ACTIVE; zero for a DISABLED topic.
     * @minimum 0
     */
  availableQuestionCount: number;
  /**
     * Distinct currently available questions in this topic with any historical attempt by this user, including attempts originally attributed to another topic.
     * @minimum 0
     */
  coveredQuestionCount: number;
  /**
     * 100 * coveredQuestionCount / availableQuestionCount for this current topic catalog. Rounded to at most two decimal places; zero when the denominator is zero.
     * @minimum 0
     * @maximum 100
     */
  coveragePercent: number;
}

export interface LearningProgressResponse {
  summary: LearningProgressSummary;
  /** All ACTIVE topics plus DISABLED topics with this user historical attempts, sorted by displayOrder, topicName, topicId. No unrelated disabled topics are exposed. */
  topics: LearningTopicProgress[];
}

export type ErrorResponseError = {
  code: string;
  message: string;
};

export interface ErrorResponse {
  error: ErrorResponseError;
}
