import { sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  pgEnum,
  pgSequence,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import { z } from "zod/v4";
import { topicsTable } from "./topics";

/**
 * Phase 3A — Question Domain Foundation.
 *
 * questionCode (e.g. CCNA-Q-000001) is generated by the DATABASE from a
 * dedicated sequence (column default), never by the client or app code, and a
 * trigger (see migration 0001) rejects any UPDATE that changes it.
 */
export const questionTypeEnum = pgEnum("question_type", ["MULTIPLE_CHOICE_SINGLE"]);
export const questionDifficultyEnum = pgEnum("question_difficulty", ["EASY", "MEDIUM", "HARD"]);
export const questionStatusEnum = pgEnum("question_status", ["ACTIVE", "DISABLED"]);

export const questionCodeSeq = pgSequence("question_code_seq", { startWith: 1, increment: 1 });

export const questionsTable = pgTable(
  "questions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    questionCode: varchar("question_code", { length: 32 })
      .notNull()
      .unique()
      .default(sql`('CCNA-Q-' || lpad(nextval('question_code_seq')::text, 6, '0'))`),
    topicId: uuid("topic_id")
      .notNull()
      .references(() => topicsTable.id, { onDelete: "restrict" }),
    text: text("text").notNull(),
    type: questionTypeEnum("type").notNull().default("MULTIPLE_CHOICE_SINGLE"),
    difficulty: questionDifficultyEnum("difficulty").notNull(),
    explanation: text("explanation").notNull().default(""),
    imageKey: varchar("image_key", { length: 512 }),
    referenceNotes: text("reference_notes"),
    status: questionStatusEnum("status").notNull().default("ACTIVE"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("questions_topic_status_idx").on(table.topicId, table.status),
    index("questions_status_idx").on(table.status),
  ],
);

export const questionOptionsTable = pgTable(
  "question_options",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    questionId: uuid("question_id")
      .notNull()
      .references(() => questionsTable.id, { onDelete: "cascade" }),
    optionKey: varchar("option_key", { length: 8 }).notNull(),
    displayOrder: integer("display_order").notNull(),
    text: text("text").notNull(),
    isCorrect: boolean("is_correct").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    unique("question_options_question_key_uq").on(table.questionId, table.optionKey),
    unique("question_options_question_order_uq").on(table.questionId, table.displayOrder),
  ],
);

export type Question = typeof questionsTable.$inferSelect;
export type QuestionOption = typeof questionOptionsTable.$inferSelect;

/** Server-side domain validation for a question option. */
export const questionOptionInputSchema = z.object({
  optionKey: z.string().trim().min(1).max(8),
  text: z.string().trim().min(1).max(4000),
  isCorrect: z.boolean(),
}).strict();

function validateQuestionOptions(
  options: { optionKey: string; isCorrect: boolean }[],
  ctx: z.RefinementCtx,
) {
  const keys = new Set(options.map((o) => o.optionKey.toUpperCase()));
  if (keys.size !== options.length) {
    ctx.addIssue({ code: "custom", path: ["options"], message: "Option keys must be unique." });
  }
  const correct = options.filter((o) => o.isCorrect).length;
  if (correct !== 1) {
    ctx.addIssue({
      code: "custom",
      path: ["options"],
      message: "MULTIPLE_CHOICE_SINGLE requires exactly one correct option.",
    });
  }
}

export const createQuestionInputSchema = z
  .object({
    topicId: z.uuid(),
    text: z.string().trim().min(1).max(10_000),
    type: z.enum(questionTypeEnum.enumValues),
    difficulty: z.enum(questionDifficultyEnum.enumValues),
    explanation: z.string().trim().max(10_000).default(""),
    imageKey: z.string().trim().max(512).nullable().default(null),
    referenceNotes: z.string().trim().max(10_000).nullable().default(null),
    status: z.enum(questionStatusEnum.enumValues).default("ACTIVE"),
    options: z.array(questionOptionInputSchema).min(2).max(10),
  })
  .strict()
  .superRefine((q, ctx) => {
    validateQuestionOptions(q.options, ctx);
  });

export type CreateQuestionInput = z.infer<typeof createQuestionInputSchema>;

/** Partial update schema; questionCode is intentionally not an accepted field. */
export const updateQuestionInputSchema = z
  .object({
    topicId: z.uuid().optional(),
    text: z.string().trim().min(1).max(10_000).optional(),
    type: z.enum(questionTypeEnum.enumValues).optional(),
    difficulty: z.enum(questionDifficultyEnum.enumValues).optional(),
    explanation: z.string().trim().max(10_000).optional(),
    imageKey: z.string().trim().max(512).nullable().optional(),
    referenceNotes: z.string().trim().max(10_000).nullable().optional(),
    status: z.enum(questionStatusEnum.enumValues).optional(),
    options: z.array(questionOptionInputSchema).min(2).max(10).optional(),
  })
  .strict()
  .superRefine((q, ctx) => {
    if (Object.keys(q).length === 0) {
      ctx.addIssue({ code: "custom", message: "At least one field must be provided." });
    }
    if (q.options) validateQuestionOptions(q.options, ctx);
  });

export type UpdateQuestionInput = z.infer<typeof updateQuestionInputSchema>;
